name: flutter_shopping_cart
description: Flutter example of shopping app using Redux architecture

dependencies:
  flutter:
    sdk: flutter

  flutter_redux: "^0.5.0"
  flutter_redux_dev_tools: "^0.3.0"
  shared_preferences: "^0.4.1"
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true